### PR TITLE
[Feature] Admin API

### PR DESCRIPTION
**Pull request by mirzahilmi**
[+] list user account approval request
[+] approve & deny user account approval request
[+] list active user
[+] delete user
[~] cast user.is_active to boolean

user account approval request json example
```json
{
  "current_page": 1,
  "data": [
    {
      "id": 1,
      "email": "miruza.dev@gmail.com",
      "name": "Mirza pengen Event-Driven",
      "phone_number": "0811111111",
      "employee_id": "EMP-2020-0000",
      "is_active": false,
      "created_at": "2024-09-09T12:48:32.000000Z",
      "updated_at": "2024-09-09T12:48:32.000000Z"
    }
  ],
  "first_page_url": "http://localhost:8000?page=1",
  "from": 1,
  "last_page": 1,
  "last_page_url": "http://localhost:8000?page=1",
  "links": [
    {
      "url": null,
      "label": "&laquo; Previous",
      "active": false
    },
    {
      "url": "http://localhost:8000?page=1",
      "label": "1",
      "active": true
    },
    {
      "url": null,
      "label": "Next &raquo;",
      "active": false
    }
  ],
  "next_page_url": null,
  "path": "http://localhost:8000",
  "per_page": 15,
  "prev_page_url": null,
  "to": 1,
  "total": 1
}
```

active user json example
```json
{
  "current_page": 1,
  "data": [
    {
      "id": 1,
      "email": "miruza.dev@gmail.com",
      "name": "Mirza pengen Event-Driven",
      "phone_number": "0811111111",
      "employee_id": "EMP-2020-0000",
      "is_active": false,
      "created_at": "2024-09-09T12:48:32.000000Z",
      "updated_at": "2024-09-09T12:48:32.000000Z"
    }
  ],
  "first_page_url": "http://localhost:8000/admin/new-users?page=1",
  "from": 1,
  "last_page": 1,
  "last_page_url": "http://localhost:8000/admin/new-users?page=1",
  "links": [
    {
      "url": null,
      "label": "&laquo; Previous",
      "active": false
    },
    {
      "url": "http://localhost:8000/admin/new-users?page=1",
      "label": "1",
      "active": true
    },
    {
      "url": null,
      "label": "Next &raquo;",
      "active": false
    }
  ],
  "next_page_url": null,
  "path": "http://localhost:8000/admin/new-users",
  "per_page": 15,
  "prev_page_url": null,
  "to": 1,
  "total": 1
}
```

tag: @mamelilea

### CODE REVIEW

**Comment by Mifaki** [comment]
mau nanya aja gda hubungan sama admin, tapi buat links yang ada di pagination di set limit ga yang label number ada berapa?

**Comment by mirzahilmi** [comment]
> mau nanya aja gda hubungan sama admin, tapi buat links yang ada di pagination di set limit ga yang label number ada berapa?

ngga di set limit, kalo ada 1500 data, harusnya bakal ada 100 link (per page 15)

**Comment by Mifaki** [comment]
> ngga di set limit, kalo ada 1500 data, harusnya bakal ada 100 link (per page 15)

menurut lu ngaruh ke load time ga?, semisal ngaruh bisa limit aja sih misal

links nya [prev, 1, current page(2), 3, 4, last page(99), next]

**Comment by mirzahilmi** [comment]
> > ngga di set limit, kalo ada 1500 data, harusnya bakal ada 100 link (per page 15)
> 
> menurut lu ngaruh ke load time ga?, semisal ngaruh bisa limit aja sih misal
> 
> links nya [prev, 1, current page(2), 3, 4, last page(99), next]

in terms of load time, ga signifikan tapi bisa kalo mau. Mau di limit berapa dari previous & next link dari current?
ex. limit 10
1, 2, 3, 4, 5, 6, 7, 8, 9, 10, [11], 12, 13, 14, 15, 16, 17, 18, 19, 20, 21

**Comment by Mifaki** [comment]
> > > ngga di set limit, kalo ada 1500 data, harusnya bakal ada 100 link (per page 15)
> > 
> > 
> > menurut lu ngaruh ke load time ga?, semisal ngaruh bisa limit aja sih misal
> > links nya [prev, 1, current page(2), 3, 4, last page(99), next]
> 
> in terms of load time, ga signifikan tapi bisa kalo mau. Mau di limit berapa dari previous & next link dari current? ex. limit 10 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, [11], 12, 13, 14, 15, 16, 17, 18, 19, 20, 21

limit 5 + last page aja

**Comment by mirzahilmi** [comment]
udah ya @Mifaki di 8f3d44d2f629b99a0912c867ddfd688476cc69e3

**Comment by mirzahilmi** [comment]
oke lets not hold back this PR more longer, ill merge it to dev as im sending this comment

**Pull request merged**
