### PR TITLE
Integrate MCR GET API

### PR DESCRIPTION
**Pull request by Mifaki**
### Changes Made
- Integrate all MCR ``Get`` Endpoint, this include ``/`` --> (mcr), ``/mcr/pending``, ``/mcr/programs``, ``/mcr/pending``, ``/mcr/programs`` 

### Field Request
- ``status`` field in programs, based on the figma ui (just sent ``boolean``, like ``is_active`` in detal)
image

### UI
image
image
image
image
image
image

### CODE REVIEW

**Comment by mirzahilmi** [comment]
i believe `is_active` field is already provided here either in dashboard page

image

or in the /mcr/programs page

image

could you reccheck it or send me a picture of the page data? @Mifaki

**Comment by Mifaki** [comment]
> i believe `is_active` field is already provided here either in dashboard page
> 
> image
> 
> or in the /mcr/programs page
> 
> image
> 
> could you reccheck it or send me a picture of the page data? @Mifaki

Ahh my bad i guess i didn't see it yesterday, i've commit a new updated the code with the ``is_active`` field @mirzahilmi 
image

**Comment by mirzahilmi** [comment]
great! i'll do some functional testing, if its working as expected i'll merge it to dev and we can move on to the next feature ;)

**Comment by mirzahilmi** [comment]
@Mifaki i believe there's an missmatch for the slicing of /mcr/pending/{program} page here?

image

**Comment by mirzahilmi** [comment]
can i have any updates for this PR?

**Comment by Mifaki** [comment]
> can i have any updates for this PR?

Will work on it today, should have an update tomorrow morning

**Comment by Mifaki** [comment]
@mirzahilmi sorry for the late update, but this pr should be done, feel free to check it again

**Comment by mirzahilmi** [comment]
> @mirzahilmi sorry for the late update, but this pr should be done, feel free to check it again

great! i'll start doing some basic qa just to make sure things goes well

**Comment by mirzahilmi** [comment]
everything looks fine including the api calling, except this part of the ui that doesnt quite the same as in the design. 

Design:
image

Slicing:
image

Im not sure if this urgent to change, what do you think? @Mifaki

**Comment by Mifaki** [comment]
> everything looks fine including the api calling, except this part of the ui that doesnt quite the same as in the design.
> 
> Design: image
> 
> Slicing: image
> 
> Im not sure if this urgent to change, what do you think? @Mifaki

not really important imo, but will fix it either way wkwkkww

**Comment by Mifaki** [comment]
@mirzahilmi done some fixing to the table design as your suggestion, for the border of select i will keep it the same cause of consistency in other form using the same ``Select`` component

image

**Review by mirzahilmi — APPROVED** [review]
Passed basic functional testing QA, LGTM

**Pull request merged**
