### PR TITLE
Integrate Editor's Pages

### PR DESCRIPTION
**Pull request by Mifaki**
### Change Made

- Integrate all of pages related to editor's role, including `Dashboard`, `Uploaded`, `Pending`, and `Program Detail`
- Fix Layout Menu `isActive` condition in editor 
- Remove `Jelajah` button since it's from the library bug's and already try every other solution but can't seems to find a way to make it work

### Bugs (related to server)
- Reload on non-Get request not working
- `some_unedited_video_programs` on Editor Dashboard is still wrap in data, hence why it's not displayed in dashboard (no need for client adjustment if it's fixed from server)
```
  "some_unedited_video_programs": {
    "current_page": 1,
    "data": [
      {
        "id": null,
        "code": "QTHNZ102",
        "slug": "porro-sunt-qui-ipsa",
        "name": "Porro sunt qui ipsa.",
        "description": "Rerum qui sed illo eveniet. Nemo blanditiis omnis officiis enim qui pariatur ut ullam. Quis nostrum ducimus asperiores aliquid molestiae provident. Totam cupiditate commodi reprehenderit dolore et quos sint.",
        "is_active": false,
        "premiere_at": "2024-11-21 05:58:35",
        "created_at": null,
        "updated_at": null,
        "program_id": 1,
        "duration": 120,
        "theme": "szoa",
        "segment_count": 9,
        "start_production": "2024-12-04",
        "episode_id": null,
        "object_id": null,
        "segment_number": null
      }
    ],
    "first_page_url": "http://localhost:8000?page=1",
    "from": 1,
    "last_page": 1,
    "last_page_url": "http://localhost:8000?page=1",
    "links": [
      {
        "url": null,
        "label": "&laquo; Previous",
        "active": false
      },
      {
        "url": "http://localhost:8000?page=1",
        "label": "1",
        "active": true
      },
      {
        "url": null,
        "label": "Next &raquo;",
        "active": false
      }
    ],
    "next_page_url": null,
    "path": "http://localhost:8000",
    "per_page": 15,
    "prev_page_url": null,
    "to": 1,
    "total": 1
  }
``` 

### UI
image
image
image
image
image

### CODE REVIEW

**Comment by mirzahilmi** [comment]
sorry for late response, will check

**Comment by mirzahilmi** [comment]
@Mifaki setelah 2 hari debugging reload page laravel coba 1001 function yang ada, solusinya cuma bisa make api browser `window.location.reload()` aja. Refactor dikit kode call api buat reload ya :+1:

**Comment by Mifaki** [comment]
@mirzahilmi sorry for the late response, but i have finished update the api call to refresh the page on success

**Comment by mirzahilmi** [comment]
@Mifaki working as expected, should be ready to be merged to dev right?


[Screencast from 2024-11-21 23-49-02.webm](https://github.com/user-attachments/assets/65698907-e289-4183-9266-285b2904c05e)

**Pull request merged**
