### PR TITLE
feat: editor service api

### PR DESCRIPTION
**Pull request by mirzahilmi**
[+] editor dashboard api
[+] editor all video uploaded programs
[+] editor pending programs
[+] upload video segment api

Dashboard Data Example
```json
{
  "all_edited_video_programs": [
    {
      "id": 1,
      "code": "NQHEW112",
      "slug": "ut-debitis-quod",
      "name": "Ut debitis quod.",
      "description": "Placeat iusto eaque unde ab tempora unde corrupti. Consequuntur voluptate perferendis deleniti quis adipisci et. Cum fugit quia rem tempore omnis tenetur sed laudantium. Qui dolor adipisci aperiam dicta est.",
      "is_active": false,
      "premiere_at": "2024-10-30 21:21:01",
      "created_at": null,
      "updated_at": null,
      "program_id": 2,
      "duration": 60,
      "theme": "nqzq",
      "segment_count": 4,
      "start_production": "2025-02-28",
      "episode_id": 3,
      "object_id": "eaamspsnrueqwdwug",
      "segment_number": 8,
      "user_id": 1,
      "video_id": 1
    }
  ],
  "some_unedited_video_programs": [
    {
      "id": 2,
      "code": "YCREU440",
      "slug": "ut-debitis-quod",
      "name": "Ut debitis quod.",
      "description": "Tempore ipsam omnis magni. At animi harum officia sit unde sit. Magni commodi sint earum id non minus dolorem velit. Eius voluptatem ipsam commodi impedit.",
      "is_active": false,
      "premiere_at": "2024-10-30 21:21:01",
      "created_at": "2024-09-29T10:43:59.000000Z",
      "updated_at": "2024-09-29T10:43:59.000000Z"
    }
  ]
}
```

Uploaded Page Data Example
```json
{
  "current_page": 1,
  "data": [
    {
      "id": 1,
      "code": "NQHEW112",
      "slug": "ut-debitis-quod",
      "name": "Ut debitis quod.",
      "description": "Placeat iusto eaque unde ab tempora unde corrupti. Consequuntur voluptate perferendis deleniti quis adipisci et. Cum fugit quia rem tempore omnis tenetur sed laudantium. Qui dolor adipisci aperiam dicta est.",
      "is_active": false,
      "premiere_at": "2024-10-30 21:21:01",
      "created_at": null,
      "updated_at": null,
      "program_id": 2,
      "duration": 60,
      "theme": "nqzq",
      "segment_count": 4,
      "start_production": "2025-02-28",
      "episode_id": 3,
      "object_id": "eaamspsnrueqwdwug",
      "segment_number": 8,
      "user_id": 1,
      "video_id": 1
    }
  ],
  "first_page_url": "http://localhost:8000/editor/uploaded?page=1",
  "from": 1,
  "last_page": 1,
  "last_page_url": "http://localhost:8000/editor/uploaded?page=1",
  "links": [
    {
      "url": null,
      "label": "&laquo; Previous",
      "active": false
    },
    {
      "url": "http://localhost:8000/editor/uploaded?page=1",
      "label": "1",
      "active": true
    },
    {
      "url": null,
      "label": "Next &raquo;",
      "active": false
    }
  ],
  "next_page_url": null,
  "path": "http://localhost:8000/editor/uploaded",
  "per_page": 15,
  "prev_page_url": null,
  "to": 1,
  "total": 1
}
```

Pending Video Program Page Data Example
```json
{
  "current_page": 1,
  "data": [
    {
      "id": null,
      "code": "PFUCA041",
      "slug": "fuga-consequatur-sit-sequi",
      "name": "Fuga consequatur sit sequi.",
      "description": "Voluptates quis assumenda aliquid corrupti qui fugiat. Corporis accusantium et ut ut ut error expedita. Asperiores odit totam omnis culpa. Rerum exercitationem eaque illum suscipit et.",
      "is_active": true,
      "premiere_at": "2025-03-31 05:46:24",
      "created_at": null,
      "updated_at": null,
      "program_id": 1,
      "duration": 60,
      "theme": "hgim",
      "segment_count": 9,
      "start_production": "2025-04-28",
      "episode_id": null,
      "object_id": null,
      "segment_number": null
    }
  ],
  "first_page_url": "http://localhost:8000/editor/pending?page=1",
  "from": 1,
  "last_page": 1,
  "last_page_url": "http://localhost:8000/editor/pending?page=1",
  "links": [
    {
      "url": null,
      "label": "&laquo; Previous",
      "active": false
    },
    {
      "url": "http://localhost:8000/editor/pending?page=1",
      "label": "1",
      "active": true
    },
    {
      "url": null,
      "label": "Next &raquo;",
      "active": false
    }
  ],
  "next_page_url": null,
  "path": "http://localhost:8000/editor/pending",
  "per_page": 15,
  "prev_page_url": null,
  "to": 1,
  "total": 1
}
```

Program Detail Page Data Example
```json
{
  "program": {
    "id": 2,
    "code": "YCREU440",
    "slug": "ut-debitis-quod",
    "name": "Ut debitis quod.",
    "description": "Tempore ipsam omnis magni. At animi harum officia sit unde sit. Magni commodi sint earum id non minus dolorem velit. Eius voluptatem ipsam commodi impedit.",
    "is_active": false,
    "premiere_at": "2024-10-30 21:21:01",
    "created_at": "2024-09-29T10:43:59.000000Z",
    "updated_at": "2024-09-29T10:43:59.000000Z",
    "episode_count": 2
  },
  "episodes": [
    {
      "id": 3,
      "program_id": 2,
      "code": "NQHEW112",
      "duration": 60,
      "theme": "nqzq",
      "segment_count": 4,
      "start_production": "2025-02-28",
      "description": "Placeat iusto eaque unde ab tempora unde corrupti. Consequuntur voluptate perferendis deleniti quis adipisci et. Cum fugit quia rem tempore omnis tenetur sed laudantium. Qui dolor adipisci aperiam dicta est.",
      "created_at": "2024-09-29T10:43:59.000000Z",
      "updated_at": "2024-09-29T10:43:59.000000Z"
    },
    {
      "id": 4,
      "program_id": 2,
      "code": "MRKEQ043",
      "duration": 30,
      "theme": "qrka",
      "segment_count": 8,
      "start_production": "2025-03-29",
      "description": "Quia fugiat quam accusantium rerum expedita vitae. Quo id facilis rerum quo ut maxime illo voluptatem. Qui odit pariatur qui omnis praesentium autem placeat.",
      "created_at": "2024-09-29T10:43:59.000000Z",
      "updated_at": "2024-09-29T10:43:59.000000Z"
    }
  ],
  "episode_with_segments": [
    [
      {
        "id": 4,
        "episode_id": 3,
        "object_id": "vmgmwqjbzbdqusrdo",
        "segment_number": 2,
        "created_at": "2024-09-29 10:43:59",
        "updated_at": "2024-09-29 10:43:59"
      }
    ],
    [
      {
        "id": 8,
        "episode_id": 4,
        "object_id": "orqmsbpomwwxecizk",
        "segment_number": 3,
        "created_at": "2024-09-29 10:43:59",
        "updated_at": "2024-09-29 10:43:59"
      },
      {
        "id": 7,
        "episode_id": 4,
        "object_id": "umegjempuywlseukj",
        "segment_number": 4,
        "created_at": "2024-09-29 10:43:59",
        "updated_at": "2024-09-29 10:43:59"
      },
      {
        "id": 12,
        "episode_id": 4,
        "object_id": "zrgnohrfpzvwuaoit",
        "segment_number": 4,
        "created_at": "2024-09-29 10:43:59",
        "updated_at": "2024-09-29 10:43:59"
      },
      {
        "id": 9,
        "episode_id": 4,
        "object_id": "qfhnwfgekgoedcpri",
        "segment_number": 5,
        "created_at": "2024-09-29 10:43:59",
        "updated_at": "2024-09-29 10:43:59"
      }
    ],
    [
      {
        "id": 3,
        "episode_id": 3,
        "object_id": "mpxkwgxgvadtsvjkg",
        "segment_number": 6,
        "created_at": "2024-09-29 10:43:59",
        "updated_at": "2024-09-29 10:43:59"
      },
      {
        "id": 2,
        "episode_id": 3,
        "object_id": "weicursgjwcvazlrx",
        "segment_number": 7,
        "created_at": "2024-09-29 10:43:59",
        "updated_at": "2024-09-29 10:43:59"
      }
    ],
    [
      {
        "id": 10,
        "episode_id": 4,
        "object_id": "ewtfcaznuketddvvi",
        "segment_number": 7,
        "created_at": "2024-09-29 10:43:59",
        "updated_at": "2024-09-29 10:43:59"
      },
      {
        "id": 6,
        "episode_id": 4,
        "object_id": "gmrceareyqkhrntpo",
        "segment_number": 7,
        "created_at": "2024-09-29 10:43:59",
        "updated_at": "2024-09-29 10:43:59"
      }
    ],
    [
      {
        "id": 1,
        "episode_id": 3,
        "object_id": "eaamspsnrueqwdwug",
        "segment_number": 8,
        "created_at": "2024-09-29 10:43:59",
        "updated_at": "2024-09-29 10:43:59"
      }
    ],
    [
      {
        "id": 11,
        "episode_id": 4,
        "object_id": "lulglkgwaovhrkrwh",
        "segment_number": 9,
        "created_at": "2024-09-29 10:43:59",
        "updated_at": "2024-09-29 10:43:59"
      },
      {
        "id": 5,
        "episode_id": 4,
        "object_id": "oaornhmlxzxrkcclb",
        "segment_number": 9,
        "created_at": "2024-09-29 10:43:59",
        "updated_at": "2024-09-29 10:43:59"
      }
    ]
  ]
}
```

### CODE REVIEW

**Comment by Mifaki** [comment]
buat detail page, possible kah buat segmen di taro di dalem episode aja, jadi gda episode_with_segmen? soalnya nanti harus gua manipulasi juga datanya di client biar jadi satu

lmk if it's to much to ask

**Comment by mirzahilmi** [comment]
> buat detail page, possible kah buat segmen di taro di dalem episode aja, jadi gda episode_with_segmen? soalnya nanti harus gua manipulasi juga datanya di client biar jadi satu
> 
> lmk if it's to much to ask

hmm, let me see

**Comment by mirzahilmi** [comment]
kaya gini cukup? @Mifaki 
```json
{
  "program": {
    "id": 2,
    "code": "LQZEP213",
    "slug": "perspiciatis-sunt-eum",
    "name": "Perspiciatis sunt eum.",
    "description": "Soluta rem ipsa autem. Molestiae tempore soluta eum sit. Illum quibusdam sapiente delectus corrupti.",
    "is_active": false,
    "premiere_at": "2025-03-28 05:37:14",
    "created_at": "2024-10-01T00:54:29.000000Z",
    "updated_at": "2024-10-01T00:54:29.000000Z",
    "episode_count": 2
  },
  "episodes": [
    {
      "id": 3,
      "program_id": 2,
      "code": "AJBND134",
      "duration": 90,
      "theme": "olvp",
      "segment_count": 9,
      "start_production": "2024-11-08",
      "description": "Nam aut sit qui voluptatem. Voluptate et in fugit officiis aut placeat temporibus. Quia facere eos occaecati esse qui.",
      "created_at": "2024-10-01T00:54:30.000000Z",
      "updated_at": "2024-10-01T00:54:30.000000Z",
      "videos": [
        {
          "id": 1,
          "episode_id": 3,
          "object_id": "imimkhavzyevlvkmb",
          "segment_number": 3,
          "created_at": "2024-10-01T00:54:30.000000Z",
          "updated_at": "2024-10-01T00:54:30.000000Z"
        },
        {
          "id": 4,
          "episode_id": 3,
          "object_id": "xsxnogjdioocbgagw",
          "segment_number": 3,
          "created_at": "2024-10-01T00:54:30.000000Z",
          "updated_at": "2024-10-01T00:54:30.000000Z"
        },
        {
          "id": 3,
          "episode_id": 3,
          "object_id": "txppkbiwnuvouvlad",
          "segment_number": 5,
          "created_at": "2024-10-01T00:54:30.000000Z",
          "updated_at": "2024-10-01T00:54:30.000000Z"
        },
        {
          "id": 5,
          "episode_id": 3,
          "object_id": "qlmbpgiujfhcdybvt",
          "segment_number": 5,
          "created_at": "2024-10-01T00:54:30.000000Z",
          "updated_at": "2024-10-01T00:54:30.000000Z"
        },
        {
          "id": 9,
          "episode_id": 3,
          "object_id": "xpihxfoemztoubivu",
          "segment_number": 5,
          "created_at": "2024-10-01T00:54:30.000000Z",
          "updated_at": "2024-10-01T00:54:30.000000Z"
        },
        {
          "id": 6,
          "episode_id": 3,
          "object_id": "yayurlydwaojdjgcm",
          "segment_number": 6,
          "created_at": "2024-10-01T00:54:30.000000Z",
          "updated_at": "2024-10-01T00:54:30.000000Z"
        },
        {
          "id": 2,
          "episode_id": 3,
          "object_id": "sgbswikhzdgwftctu",
          "segment_number": 9,
          "created_at": "2024-10-01T00:54:30.000000Z",
          "updated_at": "2024-10-01T00:54:30.000000Z"
        },
        {
          "id": 7,
          "episode_id": 3,
          "object_id": "fgmjvpufeabhzgqri",
          "segment_number": 9,
          "created_at": "2024-10-01T00:54:30.000000Z",
          "updated_at": "2024-10-01T00:54:30.000000Z"
        },
        {
          "id": 8,
          "episode_id": 3,
          "object_id": "ujbeikdcuyfnxghpj",
          "segment_number": 9,
          "created_at": "2024-10-01T00:54:30.000000Z",
          "updated_at": "2024-10-01T00:54:30.000000Z"
        }
      ]
    },
    {
      "id": 4,
      "program_id": 2,
      "code": "SXWCH124",
      "duration": 30,
      "theme": "ffsz",
      "segment_count": 7,
      "start_production": "2025-01-25",
      "description": "Totam quia distinctio maxime sed provident. Accusantium maxime ab numquam non. Sint laudantium quo molestiae vero modi est quos.",
      "created_at": "2024-10-01T00:54:30.000000Z",
      "updated_at": "2024-10-01T00:54:30.000000Z",
      "videos": [
        {
          "id": 16,
          "episode_id": 4,
          "object_id": "hngvjaszrafupkukj",
          "segment_number": 1,
          "created_at": "2024-10-01T00:54:30.000000Z",
          "updated_at": "2024-10-01T00:54:30.000000Z"
        },
        {
          "id": 15,
          "episode_id": 4,
          "object_id": "lhzvkkfltfoelbhox",
          "segment_number": 2,
          "created_at": "2024-10-01T00:54:30.000000Z",
          "updated_at": "2024-10-01T00:54:30.000000Z"
        },
        {
          "id": 12,
          "episode_id": 4,
          "object_id": "aeijmewbdhpgtzntr",
          "segment_number": 6,
          "created_at": "2024-10-01T00:54:30.000000Z",
          "updated_at": "2024-10-01T00:54:30.000000Z"
        },
        {
          "id": 11,
          "episode_id": 4,
          "object_id": "zokkxzrtficiijjka",
          "segment_number": 8,
          "created_at": "2024-10-01T00:54:30.000000Z",
          "updated_at": "2024-10-01T00:54:30.000000Z"
        },
        {
          "id": 13,
          "episode_id": 4,
          "object_id": "lkdfkiegxnevvpezj",
          "segment_number": 8,
          "created_at": "2024-10-01T00:54:30.000000Z",
          "updated_at": "2024-10-01T00:54:30.000000Z"
        },
        {
          "id": 10,
          "episode_id": 4,
          "object_id": "hqbvjfwgrmufvrvow",
          "segment_number": 9,
          "created_at": "2024-10-01T00:54:30.000000Z",
          "updated_at": "2024-10-01T00:54:30.000000Z"
        },
        {
          "id": 14,
          "episode_id": 4,
          "object_id": "piezolkjfstfzykfc",
          "segment_number": 9,
          "created_at": "2024-10-01T00:54:30.000000Z",
          "updated_at": "2024-10-01T00:54:30.000000Z"
        }
      ]
    }
  ]
}
```

**Comment by Mifaki** [comment]
mau nanya aja jadi, segmen ga harus berurut ya bisa 3, 5, 7, 8?

**Comment by mirzahilmi** [comment]
> mau nanya aja jadi, segmen ga harus berurut ya bisa 3, 5, 7, 8?

urut, itu cuma data seedernya aja

**Comment by Mifaki** [comment]
LGTM

**Pull request merged**
